/*
 * demo
 *
 * simple demo for testing android
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"

	fc "./func"
)

//InstallApp for method to install apk file
func InstallApp(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusOK)
	switch r.Method {
	case "GET":
		// fmt.Println("Parse html file...")
		fmt.Fprintf(w, "Please post the path of the apk to install")
	case "POST":
		fc.Install(w, r)
	}

}

//Open  Method to open specific file
func Open(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusOK)
	switch r.Method {
	case "GET":
		// fmt.Println("Parse html file...")
		fmt.Fprintf(w, "Please post the package to open")
	case "POST":
		fc.OpenPackage(w, r)
	}
}

//ShowPackage methodto show all package avaliable
func ShowPackage(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusOK)
	fc.ListPackage(w, r)
}
