/*
 * demo
 *
 * simple demo for testing android
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

//Route display all routes
type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

//Routes contain lists of Route
type Routes []Route

//NewRouter create new Routes
func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

//Index show homepage
func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Welcome to Android controller demo")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/home/",
		Index,
	},

	Route{
		"InstallApp",
		strings.ToUpper("Post"),
		"/home/install/",
		InstallApp,
	},

	Route{
		"InstallApp",
		"GET",
		"/home/install/",
		InstallApp,
	},

	Route{
		"Open",
		"GET",
		"/home/open/",
		Open,
	},

	Route{
		"Open",
		strings.ToUpper("Post"),
		"/home/open/",
		Open,
	},

	Route{
		"ShowPackage",
		strings.ToUpper("Get"),
		"/home/showPackage/",
		ShowPackage,
	},
}
