---
swagger: "2.0"
info:
  description: "simple demo for testing android"
  version: "1.0.0"
  title: "demo"
tags:
- name: "Android"
  description: "Android controller"
schemes:
- "https"
- "http"
basePath: "/v1/cloud-phone"
paths:
  /package/open-package/{apkId}:
    post:
      tags:
      - "app"
      summary: "open android package in server"
      description: ""
      operationId: "open"
      parameters:
      - name: "apkId"
        in: "path"
        description: "package name of the app to be opened"
        required: true
        type: "string"
        x-exportParamName: "apkId"
      responses:
        "405":
          description: "Invalid input"
  /package/install-package/{appUrl}:
    post:
      tags:
      - "app"
      summary: "install app by url"
      description: "Execute installation"
      operationId: "installApp"
      parameters:
      - name: "appUrl"
        in: "path"
        description: "URL of the app to be intalled"
        required: true
        type: "string"
        x-exportParamName: "AppUrl"
      responses:
        "200":
          description: "successful download"
        "400":
          description: "Invalid url"
        "404":
          description: "File not found"
  /package/list-package/:
    get:
      tags:
      - "app"
      summary: "show external packages and internal packages"
      description: "show packages"
      operationId: "showPackage"
      responses:
        "200":
          description: "package display"